FROM semitechnologies/weaviate:1.25.5

ENV QUERY_DEFAULTS_LIMIT=25
ENV PERSISTENCE_DATA_PATH="/var/lib/weaviate"
ENV AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED="true"
ENV ENABLE_MODULES=""
ENV DEFAULT_VECTORIZER_MODULE=""
ENV CLUSTER_HOSTNAME="node1"

EXPOSE 8080
